spring:
  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://localhost:27017/customers}
  kafka:
    bootstrap-servers: ${KAFKA_URL:kafka:9092}
    consumer:
      group-id: needLoanEventConsumerGroup
      client-id: client1
      auto-offset-reset: earliest

server:
  port: 8081
